name: Publish to pub.dev

on:
  workflow_call:  # Allow this workflow to be called by other workflows
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          architecture: x64
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get
      
      - name: Publish to pub.dev
        run: flutter pub publish --force
